@port = 3000
@host = localhost
@server_url = http://{{host}}:{{port}}/api


###

# @name get all persons
GET {{server_url}}/persons HTTP/1.1

###

# @name get server stats
GET {{server_url}}/info HTTP/1.1

###

# @name get person by id
GET {{server_url}}/persons/67eb0d62dd8d5c169e245e0a HTTP/1.1

###

# @name delete a person by id 
DELETE {{server_url}}/persons/67eb0d62dd8d5c169e245e0a HTTP/1.1

###

# @name create a new person
POST {{server_url}}/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "felix",
  "number": "134235423455"
}

###

# @name check invalid url
GET {{server_url}}/smthWhichDoesntExist HTTP/1.1

###

# @name = update a person by id 
PUT {{server_url}}/persons/67eb0d62dd8d5c169e245e0a HTTP/1.1
Content-Type: application/json

{
  "name": "felix",
  "number": "13465345"
}
