@server = "http://localhost:3000/api/blogs"

### 
# @name = get all blogs
GET {{server}}

###
# @name = create a new blog
POST {{server}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjY3ZjU2NDk3ZmY5Mzg0MDg5YjU2M2QxYSIsImlhdCI6MTc0NDEzNTMzNX0.P-b5lFmPvthq-a7rg2FZy9MSI3s0RI9WjyRYuixFahc

{
  "title": "A New Blog",
  "author": "Admin",
  "url": "http://google.com",
  "likes": 10,
  "user": "67f3f4d0c9aea98ab38fd871"
}

###
# @name = get a blog by id
GET {{server}}/67f3f60ad3a04265954d9061

### 
# @name = delete a blog
DELETE {{server}}/67f4241f7d8c429b5390bc9d
